# Generated by Django 2.1.7 on 2019-06-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planename', models.CharField(max_length=20)),
                ('echonomy', models.CharField(choices=[('E', 'Echonomy'), ('P', 'Premium Echonomy'), ('B', 'Business')], default='E', max_length=30)),
                ('source', models.CharField(choices=[('DEL', 'Delhi, India(DEL)'), ('BOM', 'Mumbai, India(BOM)'), ('BLR', 'Bangalore, India(BLR)'), ('PNQ', 'Pune, India(PNQ)'), ('HYD', 'Hyderabad, India(HYD)'), ('CCU', 'Kolkata, India(CCU)'), ('MAA', 'Chennai, India(MAA)'), ('GOI', 'Goa, India(GOI)'), ('NYC', 'New York, United State(NYC)'), ('BKK', 'Bankkok, Thailand(BKK)'), ('SIN', 'Singapore, Singapore(SIN)'), ('KTM', 'Kathmandu, Nepal(KTM)'), ('VNS', 'Varansi, India (VNS)')], default='DEL', max_length=30)),
                ('destination', models.CharField(choices=[('DEL', 'Delhi, India(DEL)'), ('BOM', 'Mumbai, India(BOM)'), ('BLR', 'Bangalore, India(BLR)'), ('PNQ', 'Pune, India(PNQ)'), ('HYD', 'Hyderabad, India(HYD)'), ('CCU', 'Kolkata, India(CCU)'), ('MAA', 'Chennai, India(MAA)'), ('GOI', 'Goa, India(GOI)'), ('NYC', 'New York, United State(NYC)'), ('BKK', 'Bankkok, Thailand(BKK)'), ('SIN', 'Singapore, Singapore(SIN)'), ('KTM', 'Kathmandu, Nepal(KTM)'), ('VNS', 'Varansi, India (VNS)')], default='VNS', max_length=30)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
