# Generated by Django 2.1.7 on 2019-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_auto_20190609_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('dtime', models.CharField(max_length=20)),
                ('atime', models.CharField(max_length=20)),
                ('payprice', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='addplane',
            name='source',
            field=models.CharField(choices=[('Delhi, India(DEL)', 'Delhi, India(DEL)'), ('Mumbai, India(BOM)', 'Mumbai, India(BOM)'), ('Bangalore, India(BLR)', 'Bangalore, India(BLR)'), ('Pune, India(PNQ)', 'Pune, India(PNQ)'), ('Hyderabad, India(HYD)', 'Hyderabad, India(HYD)'), ('Kolkata, India(CCU)', 'Kolkata, India(CCU)'), ('Chennai, India(MAA)', 'Chennai, India(MAA)'), ('Goa, India(GOI)', 'Goa, India(GOI)'), ('New York, United State(NYC)', 'New York, United State(NYC)'), ('Bankkok, Thailand(BKK)', 'Bankkok, Thailand(BKK)'), ('Singapore, Singapore(SIN)', 'Singapore, Singapore(SIN)'), ('Kathmandu, Nepal(KTM)', 'Kathmandu, Nepal(KTM)'), ('Varansi, India (VNS)', 'Varansi, India (VNS)')], default='Varansi, India(VNS)', max_length=30),
        ),
    ]
